#pragma once

#include <vector>

#include "Utils.h"

#define FORWARD_DEFINE_VK_HANDLE(object) typedef struct object##_T* object;
#if !defined(VK_NULL_HANDLE)
#define VK_NULL_HANDLE nullptr
#endif

// Forward definitions of vulkan handles and types so that we don't have to include vulkan headers in Aurorae
// headers

FORWARD_DEFINE_VK_HANDLE(VkInstance)
FORWARD_DEFINE_VK_HANDLE(VkSurfaceKHR)
FORWARD_DEFINE_VK_HANDLE(VkPhysicalDevice)
FORWARD_DEFINE_VK_HANDLE(VkDevice)
FORWARD_DEFINE_VK_HANDLE(VmaAllocator)
FORWARD_DEFINE_VK_HANDLE(VmaAllocation)
FORWARD_DEFINE_VK_HANDLE(VkBuffer)
FORWARD_DEFINE_VK_HANDLE(VkDescriptorPool)
FORWARD_DEFINE_VK_HANDLE(VkDescriptorSetLayout)
FORWARD_DEFINE_VK_HANDLE(VkDescriptorSet)
FORWARD_DEFINE_VK_HANDLE(VkShaderModule)
FORWARD_DEFINE_VK_HANDLE(VkPipelineLayout)
FORWARD_DEFINE_VK_HANDLE(VkPipelineCache)
FORWARD_DEFINE_VK_HANDLE(VkPipeline)
using VkDeviceSize = uint64_t;
using VkBufferUsageFlags = uint32_t;
enum VmaMemoryUsage : int32_t;

namespace aur {

// sync with VkDescriptorType
enum class DescriptorType : u32 {
  // VK_DESCRIPTOR_TYPE_SAMPLER = 0,
  // VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER = 1,
  // VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE = 2,
  // VK_DESCRIPTOR_TYPE_STORAGE_IMAGE = 3,
  // VK_DESCRIPTOR_TYPE_UNIFORM_TEXEL_BUFFER = 4,
  // VK_DESCRIPTOR_TYPE_STORAGE_TEXEL_BUFFER = 5,
  UniformBuffer = 6,
  // VK_DESCRIPTOR_TYPE_STORAGE_BUFFER = 7,
  // VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC = 8,
  // VK_DESCRIPTOR_TYPE_STORAGE_BUFFER_DYNAMIC = 9,
  // VK_DESCRIPTOR_TYPE_INPUT_ATTACHMENT = 10,
  // VK_DESCRIPTOR_TYPE_INLINE_UNIFORM_BLOCK = 1000138000,
  // VK_DESCRIPTOR_TYPE_ACCELERATION_STRUCTURE_KHR = 1000150000,
  // VK_DESCRIPTOR_TYPE_ACCELERATION_STRUCTURE_NV = 1000165000,
  // VK_DESCRIPTOR_TYPE_SAMPLE_WEIGHT_IMAGE_QCOM = 1000440000,
  // VK_DESCRIPTOR_TYPE_BLOCK_MATCH_IMAGE_QCOM = 1000440001,
  // VK_DESCRIPTOR_TYPE_MUTABLE_EXT = 1000351000,
  // VK_DESCRIPTOR_TYPE_PARTITIONED_ACCELERATION_STRUCTURE_NV = 1000570000,
  // VK_DESCRIPTOR_TYPE_INLINE_UNIFORM_BLOCK_EXT = VK_DESCRIPTOR_TYPE_INLINE_UNIFORM_BLOCK,
  // VK_DESCRIPTOR_TYPE_MUTABLE_VALVE = VK_DESCRIPTOR_TYPE_MUTABLE_EXT,
  // VK_DESCRIPTOR_TYPE_MAX_ENUM = 0x7FFFFFFF
};

// sync with VkShaderStageFlagBits
enum class ShaderStageType : u32 {
  Vertex = 0x00000001,
  // VK_SHADER_STAGE_TESSELLATION_CONTROL_BIT = 0x00000002,
  // VK_SHADER_STAGE_TESSELLATION_EVALUATION_BIT = 0x00000004,
  // VK_SHADER_STAGE_GEOMETRY_BIT = 0x00000008,
  Fragment = 0x00000010,
  // VK_SHADER_STAGE_COMPUTE_BIT = 0x00000020,
  // VK_SHADER_STAGE_ALL_GRAPHICS = 0x0000001F,
  // VK_SHADER_STAGE_ALL = 0x7FFFFFFF,
  // VK_SHADER_STAGE_RAYGEN_BIT_KHR = 0x00000100,
  // VK_SHADER_STAGE_ANY_HIT_BIT_KHR = 0x00000200,
  // VK_SHADER_STAGE_CLOSEST_HIT_BIT_KHR = 0x00000400,
  // VK_SHADER_STAGE_MISS_BIT_KHR = 0x00000800,
  // VK_SHADER_STAGE_INTERSECTION_BIT_KHR = 0x00001000,
  // VK_SHADER_STAGE_CALLABLE_BIT_KHR = 0x00002000,
  // VK_SHADER_STAGE_TASK_BIT_EXT = 0x00000040,
  // VK_SHADER_STAGE_MESH_BIT_EXT = 0x00000080,
  // VK_SHADER_STAGE_SUBPASS_SHADING_BIT_HUAWEI = 0x00004000,
  // VK_SHADER_STAGE_CLUSTER_CULLING_BIT_HUAWEI = 0x00080000,
  // VK_SHADER_STAGE_RAYGEN_BIT_NV = VK_SHADER_STAGE_RAYGEN_BIT_KHR,
  // VK_SHADER_STAGE_ANY_HIT_BIT_NV = VK_SHADER_STAGE_ANY_HIT_BIT_KHR,
  // VK_SHADER_STAGE_CLOSEST_HIT_BIT_NV = VK_SHADER_STAGE_CLOSEST_HIT_BIT_KHR,
  // VK_SHADER_STAGE_MISS_BIT_NV = VK_SHADER_STAGE_MISS_BIT_KHR,
  // VK_SHADER_STAGE_INTERSECTION_BIT_NV = VK_SHADER_STAGE_INTERSECTION_BIT_KHR,
  // VK_SHADER_STAGE_CALLABLE_BIT_NV = VK_SHADER_STAGE_CALLABLE_BIT_KHR,
  // VK_SHADER_STAGE_TASK_BIT_NV = VK_SHADER_STAGE_TASK_BIT_EXT,
  // VK_SHADER_STAGE_MESH_BIT_NV = VK_SHADER_STAGE_MESH_BIT_EXT,
  // VK_SHADER_STAGE_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
};

// sync with VkVertexInputRate
enum class VertexInputRate : u32 {
  Vertex = 0,
  Instance = 1,
};

// sync with VkFormat
enum class Format : u32 {
  R32_SFLOAT = 100,
  R32G32_SFLOAT = 103,
  R32G32B32_SFLOAT = 106,
  R32G32B32A32_SFLOAT = 109,
};

// sync with VkBufferUsageFlagBits
enum class BufferUsage {
  TransferSrc = 0x00000001,
  TransferDst = 0x00000002,
  Uniform = 0x00000010,
  Index = 0x00000040,
  Vertex = 0x00000080,
};

// sync with VmaMemoryUsage
enum class MemoryUsage {
  Unknown = 0,
  GpuOnly = 1,
  CpuOnly = 2,
  CpuToGpu = 3,
  GpuToCpu = 4,
};

enum class CullMode : u32 {
  None = 0,
  Front = 1,
  Back = 2,
  FrontAndBack = 3,
};

template <typename TEnum>
u32 toVkFlags(const std::vector<TEnum>& enums);

// template <typename... TEnums>
// u32 toFlagsFold(TEnums... enums) {
//   u32 flags{};
//   ((flags |= static_cast<u32>(enums)), ...);
//   return flags;
// }

} // namespace aur
